# Generated by Django 3.2.16 on 2023-03-27 21:47

from django.db import migrations
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20230325_0855'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectstatus',
            options={'ordering': (django.db.models.expressions.OrderBy(django.db.models.expressions.F('order'), nulls_last=True), 'name'), 'verbose_name': 'Статус проекта', 'verbose_name_plural': 'Статусы проекта'},
        ),
        migrations.AlterModelOptions(
            name='projecttype',
            options={'ordering': (django.db.models.expressions.OrderBy(django.db.models.expressions.F('order'), nulls_last=True), 'name'), 'verbose_name': 'Тип проекта', 'verbose_name_plural': 'Типы проекта'},
        ),
    ]
