# Generated by Django 3.2.16 on 2023-03-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20230330_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Подробное описание'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('idea', 'идея'), ('vacancy', 'идет набор'), ('in_progress', 'в процессе'), ('closed', 'закрыт')], default='idea', max_length=20, verbose_name='Статус'),
        ),
        migrations.DeleteModel(
            name='ProjectStatus',
        ),
    ]
