# Generated by Django 3.2.16 on 2023-03-31 14:48

import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20230330_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, validators=[apps.core.validators.EmailValidator()], verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='project',
            name='telegram',
            field=models.CharField(blank=True, max_length=32, null=True, validators=[django.core.validators.MinLengthValidator(5), apps.core.validators.validate_telegram_name], verbose_name='Телеграм'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_project'),
        ),
    ]
