# Generated by Django 3.2.16 on 2023-04-02 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20230331_1748'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='project',
            name='unique_project',
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('owner', 'name'), name='not_deleted_unique_project'),
        ),
    ]
