# Generated by Django 3.2.16 on 2023-04-11 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0004_auto_20230330_1626'),
        ('projects', '0008_auto_20230402_0351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Время удаления')),
                ('description', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Подробное описание')),
                ('is_published', models.BooleanField(verbose_name='Опубликована')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='participants.profession', verbose_name='Профессия')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='projects.project', verbose_name='Проект')),
            ],
            options={
                'ordering': ('-created_at',),
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
    ]
