# Generated by Django 3.2.16 on 2023-05-27 12:57

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_vacancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='telegram',
            field=models.CharField(blank=True, max_length=33, null=True, validators=[apps.core.validators.validate_telegram_name], verbose_name='Телеграм'),
        ),
    ]
