version: '3.8'

services:
  db:
    image: postgres:13.9
    restart: always
    container_name: db_local
    volumes:
      - githance_db_local:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    build:
      context: ..
      dockerfile: Dockerfile
    restart: always
    volumes:
      - static_value_local:/code/apps/staticfiles/
      - media_value_local:/code/apps/media/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.22.1-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx_default.conf:/etc/nginx/conf.d/default.conf
      - static_value_local:/var/html/static/
      - media_value_local:/var/html/media/
    depends_on:
      - backend

volumes:
  githance_db_local:
  static_value_local:
  media_value_local:
