version: '3.8'

volumes:
  githance_db_dev:
  static_value_dev:
  media_value_dev:
  static_value:
  media_value:

networks:
  private_network_dev:
    name: private_network_dev
    external: true
  nginx_network:
    name: nginx_network
    external: true

services:
  db:
    image: postgres:13.9
    restart: always
    container_name: db_dev
    volumes:
      - githance_db_dev:/var/lib/postgresql/data/
    env_file:
      - ./.env
    networks:
      - private_network_dev

  backend:
    container_name: backend_dev
    image: "${IMAGE_BACK}:${IMAGE_BACK_TAG}"
    restart: always
    volumes:
      - static_value_dev:/app/apps/staticfiles/
      - media_value_dev:/app/apps/media/
    depends_on:
      - db
    env_file:
      - ./.env
    networks:
      - private_network_dev
      - nginx_network

  nginx:
    image: nginx:1.22.1-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/srv.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
      - static_value_dev:/var/html/dev/static/
      - media_value_dev:/var/html/dev/media/
      - /etc/letsencrypt/archive/:/etc/nginx/archive/
      - /etc/letsencrypt/options-ssl-nginx.conf:/etc/nginx/options-ssl-nginx.conf
      - /etc/letsencrypt/ssl-dhparams.pem:/etc/nginx/certs/ssl-dhparams.pem
      - /etc/letsencrypt/live/githance.com/:/etc/nginx/certs/githance.com/
    depends_on:
      - backend
    networks:
      - nginx_network
