# Generated by Django 3.2.16 on 2023-03-21 13:40

import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='О себе'),
        ),
        migrations.AddField(
            model_name='user',
            name='portfolio_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на портфолио'),
        ),
        migrations.AddField(
            model_name='user',
            name='summary_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на резюме'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram',
            field=models.CharField(blank=True, max_length=32, null=True, validators=[django.core.validators.MinLengthValidator(5), apps.core.validators.validate_telegram_name], verbose_name='Телеграм'),
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
