# Generated by Django 3.2.16 on 2023-03-28 02:00

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230321_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[apps.core.validators.EmailValidator()], verbose_name='Email'),
        ),
    ]
