# Generated by Django 3.2.16 on 2023-03-27 21:47

from django.db import migrations
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0002_auto_20230325_0855'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesslevel',
            options={'ordering': (django.db.models.expressions.OrderBy(django.db.models.expressions.F('order'), nulls_last=True), 'name'), 'verbose_name': 'Уровень доступа', 'verbose_name_plural': 'Уровни доступа'},
        ),
        migrations.AlterModelOptions(
            name='profession',
            options={'ordering': (django.db.models.expressions.OrderBy(django.db.models.expressions.F('order'), nulls_last=True), 'name'), 'verbose_name': 'Профессия', 'verbose_name_plural': 'Профессии'},
        ),
    ]
