# Generated by Django 3.2.16 on 2023-03-30 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0003_auto_20230328_0047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesslevel',
            options={'verbose_name': 'Уровень доступа', 'verbose_name_plural': 'Уровни доступа'},
        ),
        migrations.AlterModelOptions(
            name='profession',
            options={'verbose_name': 'Профессия', 'verbose_name_plural': 'Профессии'},
        ),
    ]
