# Generated by Django 3.2.16 on 2023-05-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0005_accesslevel_vacancy_editing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesslevel',
            name='vacancy_editing',
        ),
        migrations.AddField(
            model_name='accesslevel',
            name='can_edit_vacancy',
            field=models.BooleanField(default=False, verbose_name='Может редактировать вакансии'),
        ),
    ]
