version: '3.8'

volumes:
  # prod
  frontend:
  staticfiles:
  mediafiles:
  # dev
  frontend_dev:
  db_dev:
  staticfiles_dev:
  mediafiles_dev:


networks:
  private_network_dev:
    name: private_network_dev
    external: true
  nginx_network:
    name: nginx_network
    external: true

services:
  db:
    container_name: db_dev
    image: postgres:13.9
    restart: always
    volumes:
      - db_dev:/var/lib/postgresql/data/
    env_file:
      - ./.env
    networks:
      - private_network_dev

  backend:
    container_name: backend_dev
    image: "${IMAGE_BACK}:${IMAGE_BACK_TAG}"
    restart: always
    volumes:
      - staticfiles_dev:/code/apps/staticfiles/
      - mediafiles_dev:/code/apps/mediafiles/
    depends_on:
      - db
    env_file:
      - ./.env
    networks:
      - private_network_dev
      - nginx_network

  # TODO:  при разработке prod nginx вынести в прод
  nginx:
    container_name: nginx_dev
    image: nginx:1.22.1-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/srv.conf:/etc/nginx/conf.d/default.conf
      # prod
      - frontend:/usr/share/nginx/html/prod/
      - staticfiles:/var/html/prod/staticfiles/
      - mediafiles:/var/html/prod/mediafiles/
      # dev
      - frontend_dev:/usr/share/nginx/html/dev/
      - staticfiles_dev:/var/html/dev/staticfiles/
      - mediafiles_dev:/var/html/dev/mediafiles/
      # ssl
      - /etc/letsencrypt/archive/:/etc/nginx/archive/
      - /etc/letsencrypt/options-ssl-nginx.conf:/etc/nginx/options-ssl-nginx.conf
      - /etc/letsencrypt/ssl-dhparams.pem:/etc/nginx/certs/ssl-dhparams.pem
      - /etc/letsencrypt/live/githance.com/:/etc/nginx/certs/githance.com/
    networks:
      - nginx_network
