name: dev.githance workflow

on:
  push:
    branches:
      - feature/deploy

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: githance_backend
  DEPLOY_PATH: GITHANCE_DEV
  DB_ENGINE: django.db.backends.postgresql
  DB_HOST: db_dev
  DB_PORT: 5432
  BACK_HOST: backend_dev

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.5

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
        pip install -r requirements.txt

    - name: Test with flake8
      run: |
        python -m flake8

  delivery-new-build:
    name: Delivery new build
    runs-on: ubuntu-latest
    needs: tests
    permissions:
      contents: read
      packages: write
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Docker login
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Set variables
        run: |
          echo REP_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
      -
        name: Build image and push to GitHub Packages
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          labels: runnumber=${GITHUB_RUN_ID}
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.REP_OWNER }}/${{ env.IMAGE_NAME }}:dev,
            ${{ env.REGISTRY }}/${{ env.REP_OWNER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
      -
        name: Copy infra files via ssh
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SRV_HOST }}
          username: ${{ secrets.SRV_USER }}
          key: ${{ secrets.SRV_SSH_KEY }}
          passphrase: ${{ secrets.SRV_SSH_PASSPHRASE }}
          source: "infra/deploy_dev/"
          rm: true
          strip_components: 2
          target: ~/${{ env.DEPLOY_PATH }}/infra
  deploy:
      runs-on: ubuntu-latest
      needs:
        - delivery-new-build
      environment:
        name: dev_deploy
      steps:
        -
          name: Executing deploy via ssh
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.SRV_HOST }}
            username: ${{ secrets.SRV_USER }}
            key: ${{ secrets.SRV_SSH_KEY }}
            passphrase: ${{ secrets.SRV_SSH_PASSPHRASE }}
            script: |
              cd ${{ env.DEPLOY_PATH }}
              ls --hide=infra | xargs -d '\n' rm -r
              cp -r infra/* .
              
              echo "IMAGE_BACK=${{ vars.IMAGE_BACK }}" > .github_vars
              echo "IMAGE_BACK_TAG=${{ vars.IMAGE_BACK_TAG }}" >> .github_vars
              chmod 600 .github_vars

              echo "DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}" > .env
              echo "DJANGO_ALLOWED_HOSTS=${{ secrets.DJANGO_ALLOWED_HOSTS }}" >> .env
              echo "DJANGO_CORS_ALLOWED_ORIGINS=${{ secrets.DJANGO_CORS_ALLOWED_ORIGINS }}" >> .env
              echo "DB_ENGINE=${{ env.DB_ENGINE }}" >> .env
              echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
              echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
              echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
              echo "DJANGO_GOOGLE_CLIENT_ID=${{ secrets.DJANGO_GOOGLE_CLIENT_ID }}" >> .env
              echo "DJANGO_GOOGLE_SECRET=${{ secrets.DJANGO_GOOGLE_SECRET }}" >> .env
              echo "DB_HOST=${{ env.DB_HOST }}" >> .env
              echo "DB_PORT=${{ env.DB_PORT }}" >> .env
              chmod 600 .env
              
              docker compose -f docker-compose_dev.yaml --env-file .github_vars pull 
              docker compose -f docker-compose_dev.yaml --env-file .github_vars down
              docker volume rm -f static_value_dev media_value_dev static_value media_value

              docker compose -f docker-compose_dev.yaml --env-file .github_vars up --detach
              
              docker compose  -f docker-compose_dev.yaml --env-file .github_vars exec -T backend python manage.py migrate
              docker compose  -f docker-compose_dev.yaml --env-file .github_vars exec -T backend python manage.py collectstatic --no-input
