name: Push tests
on:
  push:
    branches-ignore: [main, dev]

jobs:
  tests:
    name: Linters
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.5

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_dev.txt
        mv infra/deploy_local/.env.local.example .env

    - name: Running tests
      run: |
        isort --check .
        black --check .
        flake8 .
        python manage.py makemigrations --settings config.settings.dev --check
